Repository Tech-Squad-Community/techsquad-community-website, pull requests merged in 2022-03, with the labels that each got.

#29 Added a new JS Folder
  JS/script.js
  about.html
  contact.html
  index.html
  login.html
Labels: GSSoC'22, Level-2

#32 Change spelling and add information
  contact.html
Labels: GSSoC'22, Level-1

#43 Fixed Issue #41
  register.html
Labels: GSSoC'22, Level-2

#44 Fixed categories card section
  css/styles.css
  index.html
Labels: GSSoC'22, Level-2

#31 Enhanced the display
  about.html
  index.html
Labels: GSSoC'22, Level-2

#46 Upcoming events added
  about.html
  assets/img/UpcomingEventsPhotos/5thimage1.png
  assets/img/UpcomingEventsPhotos/5thimage2.png
  assets/img/UpcomingEventsPhotos/Unknown1.png
  assets/img/UpcomingEventsPhotos/VTHacks.png
  assets/img/UpcomingEventsPhotos/Vthacks2,png.png
  assets/img/UpcomingEventsPhotos/abstractHacks1.png
  assets/img/UpcomingEventsPhotos/abstractHacks2.png
  assets/img/UpcomingEventsPhotos/hackNYU1.png
  assets/img/UpcomingEventsPhotos/tuffyhacks1.png
  assets/img/UpcomingEventsPhotos/tuffyhacks2.png
  assets/img/UpcomingEventsPhotos/unknown2.png
  assets/img/UpcomingEventsPhotos/warwick.png
  assets/img/UpcomingEventsPhotos/warwick2.png
  assets/img/UpcomingEventsPhotos/wchacks.png
  assets/img/UpcomingEventsPhotos/wchacks2.png
  contact.html
  css/UpEvent.css
  index.html
  upevent.html
Labels: GSSoC'22, Level-3

#57 Added scroll to top button
  css/styles.css
  index.html
Labels: GSSoC'22, Level-2

#69 fix git command
  README.md
Labels: GSSoC22, Level1

#71 docs: Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSoC22, Level1

#77 Attached link in the quick link
  Resources.html
  index.html
Labels: GSSoC22, Level1

#85 Changed background color of card
  assets/css/quick-website.css
  index.html
Labels: GSSoC22, Level1

#87 Added toggle transition
  css/styles.css
Labels: GSSoC22, Level1

#94 added the ui files
  assets/UI design-Resouces page/Desktop - 1.svg
  assets/UI design-Resouces page/Desktop - 2.svg
  assets/UI design-Resouces page/Desktop - 3.svg
  assets/UI design-Resouces page/Desktop - 4.svg
  assets/UI design-Resouces page/link.txt
Labels: GSSoC22, Level2

#92 Issue #80
  css/styles.css
  index.html
Labels: GSSoC22, Level2

#98 Fixed : illustrations according to brand color theme
  assets/img/svg/illustrations/illustration-10.svg
  assets/img/svg/illustrations/illustration-15.svg
Labels: GSSoC22, Level3

#101 Updated upcoming events page
  assets/img/UpcomingEventsPhotos/AHackADay11.png
  assets/img/UpcomingEventsPhotos/AHackADay2.png
  assets/img/UpcomingEventsPhotos/BrickHack1.png
  assets/img/UpcomingEventsPhotos/BrickHack2.png
  assets/img/UpcomingEventsPhotos/CuHack1.png
  assets/img/UpcomingEventsPhotos/Cypher1.png
  assets/img/UpcomingEventsPhotos/GPUhack1.png
  assets/img/UpcomingEventsPhotos/GPUhack2.png
  assets/img/UpcomingEventsPhotos/Globalhack1.png
  assets/img/UpcomingEventsPhotos/Globalhack2.png
  assets/img/UpcomingEventsPhotos/HackCWRU1.png
  assets/img/UpcomingEventsPhotos/HackMerced1.png
  assets/img/UpcomingEventsPhotos/HackMerced11.png
  assets/img/UpcomingEventsPhotos/HackMerced2.png
  assets/img/UpcomingEventsPhotos/HackOwasp1.png
  assets/img/UpcomingEventsPhotos/HackOwasp2.png
  assets/img/UpcomingEventsPhotos/HackTech1.png
  assets/img/UpcomingEventsPhotos/HackTech2.png
  assets/img/UpcomingEventsPhotos/HooHacks1.png
  assets/img/UpcomingEventsPhotos/HooHacks2.png
  assets/img/UpcomingEventsPhotos/Makeathon1.png
  assets/img/UpcomingEventsPhotos/OxfordHacks11.png
  assets/img/UpcomingEventsPhotos/OxfordHacks2.png
  assets/img/UpcomingEventsPhotos/Pharmahacks1.png
  assets/img/UpcomingEventsPhotos/Pharmahacks2.png
  assets/img/UpcomingEventsPhotos/Sdu1.png
  assets/img/UpcomingEventsPhotos/Sdu2.png
  assets/img/UpcomingEventsPhotos/Tidy1.png
  assets/img/UpcomingEventsPhotos/Tidy2.png
  assets/img/UpcomingEventsPhotos/WinHacks1.png
  assets/img/UpcomingEventsPhotos/WinHacks2.png
  assets/img/UpcomingEventsPhotos/WinHacks2new.png
  assets/img/UpcomingEventsPhotos/blueprint1.png
  assets/img/UpcomingEventsPhotos/blueprint2.png
  assets/img/UpcomingEventsPhotos/bostonhacks1.png
  assets/img/UpcomingEventsPhotos/bostonhacks2.png
  assets/img/UpcomingEventsPhotos/cloudnative1.png
  assets/img/UpcomingEventsPhotos/cloudnative2.png
  assets/img/UpcomingEventsPhotos/hackhavard1.png
  assets/img/UpcomingEventsPhotos/hackhavard2.png
  assets/img/UpcomingEventsPhotos/minnehack.png
  assets/img/UpcomingEventsPhotos/polihacks1.png
  assets/img/UpcomingEventsPhotos/polihacks2.png
  assets/img/UpcomingEventsPhotos/power-up1.png
  assets/img/UpcomingEventsPhotos/revolutionUc1.png
  assets/img/UpcomingEventsPhotos/revolutionUc2.png
  assets/img/UpcomingEventsPhotos/swampack111.png
  assets/img/UpcomingEventsPhotos/swampack22.png
  assets/img/UpcomingEventsPhotos/topcoder1.png
  assets/img/UpcomingEventsPhotos/topcoder1.png'
  assets/img/UpcomingEventsPhotos/topcoder2.png
  assets/img/UpcomingEventsPhotos/yalehackhealth1.png
  assets/img/UpcomingEventsPhotos/yalehackhealth2.png
  css/UpEvent.css
  upevent.html
Labels: GSSoC22, Level3

#99 Improved About page by adding content in cards
  about.html
  css/About_Page_Css.css
Labels: GSSoC22, Level2

#106 newmorphic login and Registration page
  assets/css/log.css
  assets/css/regis.css
  login.html
  register.html
  registration.html
Labels: GSSoC22, Level3

#115 [IMPROVE] Added scrollbar
  css/styles.css
Labels: GSSoC22, Level2

#127 Resource Page created
  Resource.html
  Resources.html
  about.html
  assets/img/ResourcePage/AI.png
  assets/img/ResourcePage/BigData.jpg
  assets/img/ResourcePage/BlockChain.jpg
  assets/img/ResourcePage/Cloud.png
  assets/img/ResourcePage/ComputerNetwork.jpg
  assets/img/ResourcePage/ComputerVision.jpg
  assets/img/ResourcePage/Cryptography.png
  assets/img/ResourcePage/DSA.png
  assets/img/ResourcePage/DataMining.png
  assets/img/ResourcePage/DataScience.png
  assets/img/ResourcePage/EthicalHacking.jpg
  assets/img/ResourcePage/IoT.jpg
  assets/img/ResourcePage/android.jpg
  assets/img/ResourcePage/api.png
  assets/img/ResourcePage/css.png
  assets/img/ResourcePage/database.png
  assets/img/ResourcePage/html.png
  assets/img/ResourcePage/ios.png
  assets/img/ResourcePage/javascript.png
  assets/img/ResourcePage/ml.png
  contact.html
  css/resources.css
  index.html
  login.html
  registration.html
  upevent.html
Labels: GSSoC22, Level3

#142 Solved the bug
  css/styles.css
Labels: GSSoC22, Level2

#143 Update index.html
  index.html
Labels: GSSoC22, Level1

#156 Toggle password type enabled
  JS/password-toggle.js
  JS/script.js
  css/styles.css
  login.html
Labels: GSSoC22, Level1

#157 ISSUE: Image size adjusted
  index.html
Labels: GSSoC22, Level1

#158 Fixed content position in website
  Resource.html
  assets/js/quick-website.js
  css/resources.css
Labels: GSSoC22, Level2

#161 Added Animation in Features Section
  assets/img/shapes/4.png
  assets/img/shapes/5.svg
  assets/img/shapes/6.svg
  assets/img/shapes/7.png
  assets/img/shapes/8.png
  css/styles.css
  index.html
Labels: GSSoC22, Level3

#147 worked over Responsiveness
  css/UpEvent.css
Labels: GSSoC22, Level2

#164 Added back to top button on remaining pages
  about.html
  contact.html
Labels: GSSoC22, Level1

#165 Grid features section animation added
  css/styles.css
  index.html
Labels: GSSoC22, Level3

#172 Optimized resources page
  Resource.html
  css/resources.css
Labels: GSSoC22, Level2

#173 Animation Added on Are you ready section
  css/styles.css
  index.html
Labels: GSSoC22, Level3

#174 #162 Form validation completed
  ForgotPassword.html
  JS/Validations/Confirm_Password_Validate.js
  JS/Validations/Email_Validate.js
  JS/Validations/Name_Validate.js
  JS/Validations/Password_Validate.js
  JS/Validations/ValidateForgotPassword.js
  JS/Validations/ValidateLogin.js
  JS/Validations/ValidateRegistration.js
  login.html
  registration.html
Labels: GSSoC22, Level2

#178 #129 Fixed - Added animation on social links
  ForgotPassword.html
  Resource.html
  about.html
  contact.html
  css/About_Page_Css.css
  css/UpEvent.css
  css/resources.css
  css/styles.css
  index.html
  login.html
  registration.html
  upevent.html
Labels: GSSoC22, Level2

#182 Fixed cards minor change
  contact.html
Labels: GSSoC22, Level1

#183 #169 Footer updation completed
  ArchiveCode/footer.html
  ForgotPassword.html
  Resource.html
  about.html
  contact.html
  index.html
  login.html
  registration.html
  upevent.html
Labels: GSSoC22, Level1

#184 Fixed footer in mobile version of website
  about.html
  assets/css/quick-website.css
  contact.html
  index.html
  login.html
Labels: GSSoC22, Level2

#185 FRESH PR FOR FORM ENHANCEMENT
  assets/css/log.css
  login.html
Labels: GSSoC22, Level2
